# Generated by Django 5.2.4 on 2025-07-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditApprovalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
